controller_manager:
  ros__parameters:
    update_rate: 50
    #use_sim_time: true

    joint_state_broadcaster:
      type: joint_state_broadcaster/JointStateBroadcaster

    diff_drive_controller:
      type: diff_drive_controller/DiffDriveController

    diff_drive_controller2:
      type: diff_drive_controller/DiffDriveController

diff_drive_controller:
  ros__parameters:
    left_wheel_names: ["rueda_izq_abajo_joint"]
    right_wheel_names: ["rueda_der_abajo_joint"]

    wheel_separation: 0.3
    wheels_per_side: 1
    wheel_radius: 0.055

    

    base_frame_id: base_link
    odom_frame_id: odom
    enable_odom_tf: true
    publish_rate: 50.0

    use_stamped_vel: false


    linear.x.has_velocity_limits: false
    linear.x.has_acceleration_limits: false
    linear.x.has_jerk_limits: false
    linear.x.max_velocity: 0.0
    linear.x.min_velocity: 0.0
    linear.x.max_acceleration: 0.0
    linear.x.min_acceleration: 0.0
    linear.x.max_jerk: 0.0
    linear.x.min_jerk: 0.0

    angular.z.has_velocity_limits: false
    angular.z.has_acceleration_limits: false
    angular.z.has_jerk_limits: false
    angular.z.max_velocity: 0.0
    angular.z.min_velocity: 0.0
    angular.z.max_acceleration: 0.0
    angular.z.min_acceleration: 0.0
    angular.z.max_jerk: 0.0
    angular.z.min_jerk: 0.0


diff_drive_controller2:
  ros__parameters:
    left_wheel_names: ["rueda_izq_arriba_joint"]
    right_wheel_names: ["rueda_der_arriba_joint"]

    wheel_separation: 0.3
    wheels_per_side: 1
    wheel_radius: 0.055

    

    base_frame_id: base_link
    odom_frame_id: odom2
    enable_odom_tf: false
    publish_rate: 50.0

    use_stamped_vel: false


    linear.x.has_velocity_limits: false
    linear.x.has_acceleration_limits: false
    linear.x.has_jerk_limits: false
    linear.x.max_velocity: 0.0
    linear.x.min_velocity: 0.0
    linear.x.max_acceleration: 0.0
    linear.x.min_acceleration: 0.0
    linear.x.max_jerk: 0.0
    linear.x.min_jerk: 0.0

    angular.z.has_velocity_limits: false
    angular.z.has_acceleration_limits: false
    angular.z.has_jerk_limits: false
    angular.z.max_velocity: 0.0
    angular.z.min_velocity: 0.0
    angular.z.max_acceleration: 0.0
    angular.z.min_acceleration: 0.0
    angular.z.max_jerk: 0.0
    angular.z.min_jerk: 0.0
